FROM ubuntu

RUN apt-get update && apt-get upgrade -y && apt-get install -y nodejs npm git vim 

RUN npm install yarn --global && npm install npm --global


#NodeJS, npm, Yarn for web dev
# build&run:
# docker build -t b_ex01 .
# docker run --rm -ti b_ex01